export const GET_NEARBY_STATIONS_REQUEST = 'GET_NEARBY_STATIONS_REQUEST'
export const GET_NEARBY_STATIONS_SUCCESS = 'GET_NEARBY_STATIONS_SUCCESS'
export const GET_NEARBY_STATIONS_ERROR = 'GET_NEARBY_STATIONS_ERROR'

export const GET_NEARBY_STORES_REQUEST = 'GET_NEARBY_STORES_REQUEST'
export const GET_NEARBY_STORES_SUCCESS = 'GET_NEARBY_STORES_SUCCESS'
export const GET_NEARBY_STORES_ERROR = 'GET_NEARBY_STORES_ERROR'

export const GET_STATION_DISTS_REQUEST = 'GET_STATION_DISTS_REQUEST'
export const GET_STATION_DISTS_SUCCESS = 'GET_STATION_DISTS_SUCCESS'
export const GET_STATION_DISTS_ERROR = 'GET_STATION_DISTS_ERROR'
